CREATE DATABASE SALES
DROP DATABASE SALES
USE SALES

CREATE TABLE CLIENT (
ID_CLIENT INT PRIMARY KEY NOT NULL,
firstNameClient VARCHAR(25) NOT NULL,
lastNameClient VARCHAR(25) NOT NULL,
dateBirth DATE NOT NULL,
numberPhone VARCHAR(11) NOT NULL,
emailAddress VARCHAR(30) NOT NULL,
lastModifiet DATETIME NOT NULL,
deleteClient BIT NOT NULL)

CREATE TABLE INVOICE (
ID_INVOICE INT PRIMARY KEY NOT NULL,
FK_ID_CLIENT INT NOT NULL,
FK_ID_PRODUCT INT NOT NULL,
saleDate DATETIME NOT NULL,
comments VARCHAR(300),
lastModifiet DATETIME NOT NULL,
deleteInvoice BIT NOT NULL,
FOREIGN KEY(FK_ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
FOREIGN KEY(FK_ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT))

CREATE TABLE PRODUCT (
ID_PRODUCT INT PRIMARY KEY NOT NULL,
nameProduct VARCHAR(25) NOT NULL,
priceProduct FLOAT NOT NULL,
storageProduct INT NOT NULL CHECK(storageProduct>=5),
lastModifiet DATETIME NOT NULL,
productActive BIT NOT NULL,
deleteProduct BIT NOT NULL)

